# Generated by Django 3.2 on 2021-04-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_artcilepost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='artcilepost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d/'),
        ),
    ]
